apiVersion: v1
kind: Service
metadata:
  name: dev-deployment-service
  namespace: dev
spec:
  selector:
    app: development-deployment # This must match the label on your deployment's pods
  ports:
    - protocol: TCP
      port: 8080      # The port the LoadBalancer will listen on
      targetPort: 8080 # The port on the container to forward traffic to
  type: LoadBalancer
